#!/bin/bash

# Set the TZ environment variable
TZ=$(tzselect)

# Export the TZ variable to set the time zone for the current session
export TZ

sudo apt-get update

sudo apt-get -y install tmux 
curl -fLo ~/.tmux.conf https://raw.githubusercontent.com/zeyong-wang/dev-setup/main/.tmux.conf

sudo apt-get -y install cmake 
sudo apt-get -y install git 
sudo apt-get -y install g++ 

# Check if Vim is installed
if ! command -v nvim > /dev/null; then
  # Install Vim if it is not installed
  sudo apt-get install vim
fi
# install neovim
curl -fLo ~/nvim-linux64.deb https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
sudo apt-get -y install ~/nvim-linux64.deb
# config and install plugins
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
# copy config files
curl -fLo ~/.vimrc https://raw.githubusercontent.com/zeyong-wang/dev-setup/main/.vimrc
curl -fLo ~/.config/nvim/init.vim --create-dirs https://raw.githubusercontent.com/zeyong-wang/dev-setup/main/init.vim
curl -fLo ~/.config/nvim/lua/plugins.lua --create-dirs https://raw.githubusercontent.com/zeyong-wang/dev-setup/main/plugins.lua
curl -fLo ~/.config/nvim/lua/nvim-tree-setup.lua --create-dirs https://raw.githubusercontent.com/zeyong-wang/dev-setup/main/nvim-tree-setup.lua
#nvim -c "PackerInstall" -c "qa"
