#!/bin/bash

# Set the TZ environment variable
#TZ=$(tzselect)

# Export the TZ variable to set the time zone for the current session
#export TZ

sudo apt-get update

sudo apt-get -y install tmux 
sudo apt-get -y install cmake 
sudo apt-get -y install git 
sudo apt-get -y install g++ 

# Check if Vim is installed
if ! command -v nvim > /dev/null; then
  # Install Vim if it is not installed
  sudo apt-get install vim
fi
# install neovim
curl -O https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
sudo apt-get -y install ./nvim-linux64.deb
mkdir -p .config/nvim/
# copy init.vim to .config/nvim/
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
mkdir -p .config/nvim/lua/
# copy plugins.lua
#curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
#    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#nvim -c "PlugInstall" -c "qa"
